test

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -15,10 +15,19 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Get Node.js version from package.json
+        run: |
+          NODE_VERSION=$(jq -r '.volta.node' package.json)
+          if [ -z "$NODE_VERSION" ]; then
+            echo "Error: No Node.js version found in package.json under .volta.node"
+            exit 1
+          fi
+          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
+
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: $(jq -r '.volta.node' package.json)
+          node-version: ${{ env.NODE_VERSION }}
 
       - run: yarn --immutable
 
